### ISSUE TITLE
Why could a UDP conversation has a non-zero dst_bytes

### ISSUE THREAD

**Issue by FlyingOnion** [AI-IDS/kdd99_feature_extractor#3]
I'm sorry I cannot find where they are merged into one conversation.

**Comment by bittomix** [comment]
Hi FlyingOnion,

an UDP conversation can be identified by following tuple `<src_ip, src_port, dst_ip, dst_port>`. For response from server to client only the source and destination fields are exchanged. 

The actual merging takes place in [`ConversationReconstructor::add_packet()`](https://github.com/AI-IDS/kdd99_feature_extractor/blob/master/src/ConversationReconstructor.cpp#L39) by trying to assign the packet to conversation in in conversation map. **In case of failure opposite direction is tried.** For unassigned packets new conversation is created.
