### ISSUE TITLE
A question about running this program on PCAP file.

### ISSUE THREAD

**Issue by entelecheiaZ** [AI-IDS/kdd99_feature_extractor#4]
Hi bittomix:
    We try to use this program to generate features from PCAP files. But we don't know how because we are not familiar with CPP. So can you help us?
    Thank you !

**Comment by bittomix** [comment]
Hi entelecheiaZ,
you can open pcap file by simply passing the file as last argument, for example: 
```kdd99extractor capture1.pcap```

You can also redirect the output to file specified using `-o` switch. All command line options can be display using `kdd99extractor --help`.

**Comment by clarybits** [comment]
Hi bittomix,
How do I pass the file as a last argument in cpp? Kindly throw more light

**Comment by frknozr** [comment]
You can use jetbrains clion for compiling. After compiling, you should edit program argument option(with edit configuration button).

**Comment by d3vn0mi** [comment]
hello @frknozr  i am having troubles compiling with clion , care to elaborate? Thanks in advance

EDIT: Library was missing
Building instructions for future references:
-Download CLion IDE
-Download the project and import it to CLion
-edit the first line of every file in src **#include <cstddef>**
-build all
-Add arguments through configuration "" /home/mypath/mypcap.pcap "" and run kdd99extractor

**Comment by cpsc-animesh** [comment]
Hi @clarybits All you need is this video to compile and run this program:
https://www.youtube.com/watch?v=HPMvU64RUTY

**Comment by bittomix** [comment]
> Hi bittomix,
> How do I pass the file as a last argument in cpp? Kindly throw more light

Hi @clarybits, 
You pass it to executable created by compiling the source code in a regular way:
1. compile this tool. 
2. then launch a command line/shell, change to directory containing the created executable file kdd99extractor
3. run the command: `kdd99extractor <path-to-your-pcap-file>`

bittomix
