### ISSUE TITLE
DARPA 2000 DATASET

### ISSUE THREAD

**Issue by Mohd-210** [AI-IDS/kdd99_feature_extractor#8]
Hi bittomix:

Is it possible to run this program using DARPA 2000 dataset ( TCPDUMP). 

Regards

**Comment by bittomix** [comment]
Hi @Mohd-210,

sorry for late response. Tcpdump actually uses libpcap on Linux, BSD and macOS operating systems. So this should be the native format for input.

Hint: In case you need use other input formats or do some trivial filtering of packets, [thark](https://www.wireshark.org/docs/man-pages/tshark.html) (part of Wireshark) might be the tool of choice.

bittomix
