### ISSUE TITLE
I got a problem about pcap file

### ISSUE THREAD

**Issue by cainsmile** [AI-IDS/kdd99_feature_extractor#9]
![qq 20180402161243](https://user-images.githubusercontent.com/25003290/38189001-c8615052-3690-11e8-8dbd-5185a1148358.png)
Is the problem about the directory of pcap file? what should i do?

**Comment by avishka40** [comment]
Did you find a resolution for this ?
Edit: Its just a matter of installing libpcap

**Comment by bittomix** [comment]
Hi @cainsmile,

sorry for late response.  In case you have not solved the issue yet, I assume there might be two causes of it:
1. Either you do not have WinPCap/libpcap installed (as @avishka40 wrote)
2. Or it is installed in unusual path.

In the first case you need to install WinPCap (on Windows, your case) or libpcap (on Linux)

In the second case you have two options to specify your.
- You can either add hint for PCAP_INCLUDE_DIR (path to includes for pcap library) in [`cmake/FindPCAP.cmake`](/AI-IDS/kdd99_feature_extractor/blob/master/cmake/FindPCAP.cmake#L25). This will instruct cmake to look or pcap include files in this directory.
- You can set the variable for include path as command line argument for cmake - for example:
`cmake -DPCAP_INCLUDE_DIR="<your-pcap-include-path>"  <other-options-and-arguments>`
This pcap include path sould contain file "pcap.h".

Hope this will help you or somebody else.
bittomix
